# Generated by Django 5.2.6 on 2025-09-25 18:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chance',
            fields=[
                ('cod_projects', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('staff_presale', models.CharField(max_length=100)),
                ('cost_center', models.CharField(max_length=20)),
                ('com_exe', models.CharField(max_length=100)),
                ('regis_date', models.DateField(auto_now_add=True)),
                ('dres_chance', models.CharField(max_length=255)),
                ('date_aprox_close', models.DateField(blank=True, null=True)),
                ('cost_aprox_chance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('aprox_uti', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'db_table': 'chance',
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('ruc_costumer', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('com_name', models.CharField(max_length=255)),
                ('type_costumer', models.CharField(choices=[('Corporativo', 'Cliente Corporativo'), ('PYME', 'Pequeña y Mediana Empresa'), ('Individual', 'Cliente Individual'), ('Gobierno', 'Entidad Gubernamental')], default='Individual', max_length=20)),
                ('contac_costumer', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'costumer',
            },
        ),
        migrations.CreateModel(
            name='Presale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.CharField(max_length=100)),
                ('job_name', models.CharField(max_length=200)),
                ('contract_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('material_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Labor cost (h-h)')),
                ('subcontracted_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overhead_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Respon',
            fields=[
                ('emplo_cod', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'respon',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('ruc_supplier', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_supplier', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'supplier',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('cod_projects', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='projects.chance')),
                ('state_projects', models.CharField(choices=[('Planeado', 'Planeado'), ('En Progreso', 'En Progreso'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('estimated_end_date', models.DateField(blank=True, null=True)),
                ('respon_projects', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.respon')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='chance',
            name='info_costumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.costumer'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('code_art', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('part_number', models.CharField(max_length=100)),
                ('descrip', models.CharField(blank=True, max_length=255)),
                ('manufac', models.CharField(max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('ruc_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.supplier')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_number', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('initial_delivery_date', models.DateField()),
                ('final_delivery_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('po_status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Parcial'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], max_length=30)),
                ('observations', models.TextField(blank=True)),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projects')),
            ],
            options={
                'db_table': 'purchase_order',
            },
        ),
        migrations.CreateModel(
            name='Hoursrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respon', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('acti', models.CharField(blank=True, max_length=200, null=True)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horas', to='projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_center', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('job_name', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('cost_material', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_h', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('outsourced', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('overhead_costs', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('regis_date', models.DateField(default=django.utils.timezone.now)),
                ('month', models.CharField(editable=False, max_length=20)),
                ('amount', models.FloatField(default=0, editable=False, validators=[django.core.validators.MinValueValidator(0)])),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='projects.projects')),
            ],
        ),
        migrations.CreateModel(
            name='PODetailProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.PositiveIntegerField()),
                ('unit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.product')),
                ('po_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.purchaseorder')),
            ],
            options={
                'db_table': 'po_detail_product',
                'unique_together': {('po_number', 'product_code')},
            },
        ),
    ]
