# Generated by Django 5.2.6 on 2025-10-01 14:55

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presale',
            name='chance',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='presale', to='projects.chance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateField(default=datetime.datetime(2025, 10, 1, 14, 55, 52, 463805, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='presale',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto contractual'),
        ),
        migrations.AlterField(
            model_name='presale',
            name='cost_center',
            field=models.CharField(max_length=100, verbose_name='Centro de costo'),
        ),
        migrations.AlterField(
            model_name='presale',
            name='job_name',
            field=models.CharField(max_length=200, verbose_name='Nombre del proyecto'),
        ),
        migrations.AlterField(
            model_name='presale',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo servicios h-h'),
        ),
        migrations.AlterField(
            model_name='presale',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo material'),
        ),
        migrations.AlterField(
            model_name='presale',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo gastos generales/otros'),
        ),
        migrations.AlterField(
            model_name='presale',
            name='subcontracted_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo subcontratado'),
        ),
        migrations.AlterField(
            model_name='presale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo total'),
        ),
    ]
