# Generated by Django 5.2.6 on 2025-10-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_presale_chance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='podetailproduct',
            old_name='product_code',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='podetailproduct',
            old_name='po_number',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='podetailproduct',
            old_name='units',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='podetailproduct',
            old_name='unit_amount',
            new_name='unit_price',
        ),
        migrations.AlterUniqueTogether(
            name='podetailproduct',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='podetailproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterModelTable(
            name='podetailproduct',
            table=None,
        ),
        migrations.CreateModel(
            name='PODetailSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_date', models.DateField()),
                ('supplier_status', models.CharField(max_length=30)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.supplier')),
            ],
        ),
        migrations.RemoveField(
            model_name='podetailproduct',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='podetailproduct',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='podetailproduct',
            name='tax',
        ),
    ]
