# Generated by Django 5.2.6 on 2025-10-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_rename_product_code_podetailproduct_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetailproduct',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='podetailproduct',
            name='igv',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='podetailproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='podetailproduct',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='podetailsupplier',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterModelTable(
            name='podetailproduct',
            table='po_detail_product',
        ),
        migrations.AlterModelTable(
            name='podetailsupplier',
            table='po_detail_supplier',
        ),
    ]
