# Generated by Django 5.2.6 on 2025-10-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_podetailproduct_comment_podetailproduct_igv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetailproduct',
            name='measurement_unit',
            field=models.CharField(choices=[('unidades', 'Unidades'), ('m²', 'Metros Cuadrados'), ('m', 'Metros Lineales'), ('kg', 'Kilogramos'), ('lt', 'Litros'), ('gl', 'Galones'), ('caja', 'Cajas'), ('juego', 'Juegos')], default='unidades', max_length=20, verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo'),
        ),
    ]
