# Generated by Django 5.2.6 on 2025-10-06 16:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_podetailproduct_measurement_unit_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetailproduct',
            name='local_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='projects',
            name='cost_center',
            field=models.CharField(default='SIN-CENTRO', max_length=20),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=8, verbose_name='Tipo de Cambio'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='guide_date',
            field=models.DateField(blank=True, null=True, verbose_name='Guide/Receipt Date'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='guide_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Guide/Receipt Number'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Número de Factura')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión')),
                ('invoice_type', models.CharField(choices=[('invoice', 'Factura'), ('receipt', 'Boleta'), ('ticket', 'Ticket')], default='invoice', max_length=20, verbose_name='Tipo de Comprobante')),
                ('supplier_ruc', models.CharField(max_length=20, verbose_name='RUC Proveedor')),
                ('supplier_name', models.CharField(max_length=255, verbose_name='Nombre Proveedor')),
                ('supplier_address', models.CharField(blank=True, max_length=500, verbose_name='Dirección Proveedor')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='IGV/Impuestos')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total Factura')),
                ('currency', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares'), ('EUR', 'Euros')], default='PEN', max_length=10, verbose_name='Moneda')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=8, verbose_name='Tipo de Cambio')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoices/pdf/', verbose_name='PDF Factura')),
                ('xml_file', models.FileField(blank=True, null=True, upload_to='invoices/xml/', verbose_name='XML Factura')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.purchaseorder', verbose_name='Orden de Compra relacionada')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'invoice',
                'ordering': ['-issue_date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_description', models.CharField(max_length=255, verbose_name='Descripción en Factura')),
                ('product_code', models.CharField(blank=True, max_length=100, verbose_name='Código en Factura')),
                ('product_brand', models.CharField(blank=True, max_length=100, verbose_name='Marca en Factura')),
                ('product_model', models.CharField(blank=True, max_length=100, verbose_name='Modelo en Factura')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Precio Unitario en Factura')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal en Factura')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to='projects.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.product', verbose_name='Producto del Catálogo')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'db_table': 'invoice_detail',
            },
        ),
    ]
