# Generated by Django 5.2.6 on 2025-10-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_podetailproduct_local_total_projects_cost_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podetailproduct',
            name='measurement_unit',
            field=models.CharField(choices=[('unidades', 'Unidades'), ('m²', 'Metros Cuadrados'), ('m', 'Metros Lineales'), ('kg', 'Kilogramos'), ('lt', 'Litros'), ('gl', 'Galones'), ('caja', 'Cajas'), ('juego', 'Juegos')], default='unidades', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='guide_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='guide_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
