# Generated by Django 5.2.6 on 2025-10-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_podetailproduct_measurement_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='podetailsupplier',
            name='status_factura_contabilidad',
            field=models.CharField(blank=True, max_length=50, verbose_name='Status Factura Contabilidad'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=100, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='local_import',
            field=models.CharField(choices=[('LOCAL', 'Local'), ('IMPORT', 'Importado')], default='LOCAL', max_length=10, verbose_name='Local/Import'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='pagar_a',
            field=models.CharField(blank=True, max_length=255, verbose_name='Pagar A'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='te',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo de Entrega (días)'),
        ),
    ]
