# Generated by Django 5.2.6 on 2025-10-07 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_podetailsupplier_status_factura_contabilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='presale_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.presale'),
        ),
    ]
