# Generated by Django 5.2.6 on 2025-10-08 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_purchaseorder_presale_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='presale_source',
        ),
    ]
