# Generated by Django 5.2.6 on 2025-10-08 17:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_remove_purchaseorder_presale_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarnedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curve_data', models.JSONField(default=dict, help_text='Datos para el gráfico: {months: [], pv: [], ev: [], ac: []}')),
                ('bac', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cpi', models.DecimalField(decimal_places=3, default=1.0, max_digits=6)),
                ('spi', models.DecimalField(decimal_places=3, default=1.0, max_digits=6)),
                ('cv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('eac', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('etc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('analysis_date', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='earned_value', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Análisis de Valor Ganado',
                'verbose_name_plural': 'Análisis de Valor Ganado',
                'db_table': 'earned_value',
            },
        ),
        migrations.CreateModel(
            name='ProjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_number', models.IntegerField(help_text='Mes 1, 2, 3...', verbose_name='Número de mes')),
                ('planned_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje programado para este mes', max_digits=5, verbose_name='% Avance Programado')),
                ('actual_percentage', models.DecimalField(decimal_places=2, help_text='Porcentaje real completado', max_digits=5, verbose_name='% Avance Real')),
                ('record_date', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Avance de Proyecto',
                'verbose_name_plural': 'Avances de Proyectos',
                'db_table': 'project_progress',
                'unique_together': {('project', 'month_number')},
            },
        ),
    ]
