# Generated by Django 5.2.6 on 2025-10-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_add_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presale',
            name='estimated_duration',
        ),
        migrations.DeleteModel(
            name='EarnedValue',
        ),
    ]
