# Generated by Django 5.2.6 on 2025-10-08 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_remove_presale_estimated_duration_delete_earnedvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='presale',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=8, help_text='Duración total del proyecto en meses', verbose_name='Duración Estimada (meses)'),
        ),
    ]
