# Generated by Django 5.2.6 on 2025-10-08 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_presale_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='estimated_duration',
            field=models.PositiveIntegerField(default=8),
        ),
    ]
