# Generated by Django 5.2.6 on 2025-10-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_projects_estimated_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presale',
            name='estimated_duration',
            field=models.PositiveIntegerField(help_text='Duración total del proyecto en meses (1-36)', verbose_name='Duración Estimada (meses)'),
        ),
    ]
