# Generated by Django 5.2.6 on 2025-10-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_alter_invoice_purchase_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Nº Factura')),
                ('invoice_date', models.DateField(verbose_name='Fecha Emisión')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Facturado')),
                ('description', models.CharField(help_text='Ej: Avance 30% - Instalación equipos', max_length=255, verbose_name='Concepto')),
                ('payment_status', models.CharField(choices=[('EMITIDA', 'Emitida'), ('COBRADA', 'Cobrada'), ('VENCIDA', 'Vencida')], default='EMITIDA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoices', to='projects.projects')),
            ],
            options={
                'db_table': 'client_invoices',
                'ordering': ['invoice_date'],
            },
        ),
    ]
