# Generated by Django 5.2.6 on 2025-10-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_clientinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='last_progress_update',
            field=models.DateField(blank=True, null=True, verbose_name='Última actualización avance'),
        ),
        migrations.AddField(
            model_name='projects',
            name='physical_percent_complete',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje real de avance físico según PMI', max_digits=5, verbose_name='% Avance Físico (PMI)'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('EN_PROCESO', 'En Proceso'), ('ENTREGADO - PAGO PENDIENTE', 'Entregado - Pago Pendiente'), ('ENTREGADO Y PAGADO', 'Entregado y Pagado'), ('SERVICIO', 'Servicio'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50),
        ),
    ]
