# Generated by Django 5.2.6 on 2025-10-14 22:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_projects_last_progress_update_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Instalación puntos de red, Configuración equipos, etc.', max_length=200, verbose_name='Nombre de la actividad')),
                ('description', models.TextField(blank=True, help_text='Detalles específicos de la actividad', verbose_name='Descripción')),
                ('complexity', models.IntegerField(choices=[(1, '1 - Básico'), (2, '2'), (3, '3 - Medio'), (4, '4'), (5, '5 - Avanzado')], help_text='1=Básico, 5=Avanzado', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Complejidad técnica')),
                ('effort', models.IntegerField(choices=[(1, '1 - Bajo'), (2, '2'), (3, '3 - Medio'), (4, '4'), (5, '5 - Alto')], help_text='1=Poco esfuerzo, 5=Mucho esfuerzo', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Esfuerzo estimado')),
                ('impact', models.IntegerField(choices=[(1, '1 - Bajo'), (2, '2'), (3, '3 - Medio'), (4, '4'), (5, '5 - Crítico')], help_text='1=Bajo impacto, 5=Crítico', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Impacto en el proyecto')),
                ('calculated_weight', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculado automáticamente basado en complejidad, esfuerzo e impacto', max_digits=5, verbose_name='Peso calculado (%)')),
                ('unit_of_measure', models.CharField(help_text='Ej: puntos, equipos, metros, pruebas, etc.', max_length=50, verbose_name='Unidad de medida')),
                ('total_units', models.IntegerField(help_text='Cantidad total a completar', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total de unidades')),
                ('completed_units', models.IntegerField(default=0, help_text='Cantidad actualmente completada', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unidades completadas')),
                ('percentage_completed', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculado automáticamente: (completadas / total) * 100', max_digits=5, verbose_name='Porcentaje completado')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.projects', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Actividad del proyecto',
                'verbose_name_plural': 'Actividades del proyecto',
                'ordering': ['-calculated_weight', 'name'],
                'indexes': [models.Index(fields=['project', 'is_active'], name='projects_pr_project_90d29d_idx'), models.Index(fields=['calculated_weight'], name='projects_pr_calcula_26dc7e_idx')],
            },
        ),
    ]
