# Generated by Django 5.2.6 on 2025-10-15 00:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0021_projectactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientinvoice',
            options={'ordering': ['-invoice_date', 'invoice_number'], 'verbose_name': 'Factura Cliente', 'verbose_name_plural': 'Facturas Clientes'},
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='bank_confirmation_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código Confirmación Banco'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='bank_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia Bancaria'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='bank_verified_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Verificación Banco'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='client_notes',
            field=models.TextField(blank=True, verbose_name='Comentarios del Cliente'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='fully_paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Pago Completo'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='Notas Internas'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='invoice_file',
            field=models.FileField(blank=True, help_text='PDF o imagen de la factura emitida', null=True, upload_to='client_invoices/%Y/%m/', verbose_name='Archivo Factura'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='is_urgent',
            field=models.BooleanField(default=False, verbose_name='Urgente'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Pagado'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='payment_reported_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Reporte Pago'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='reminder_sent',
            field=models.BooleanField(default=False, verbose_name='Recordatorio Enviado'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='status',
            field=models.CharField(choices=[('BORRADOR', '📝 Borrador'), ('EMITIDA', '✅ Factura Emitida'), ('PAGO_REPORTADO', '🟡 Pago Reportado por Cliente'), ('PAGO_VERIFICADO', '🔵 Pago Verificado en Banco'), ('PAGADA', '💰 Pagada Confirmada'), ('VENCIDA', '❌ Vencida'), ('PAGO_NO_RECIBIDO', '🚨 Pago No Recibido'), ('CONTROVERSIA', '⚖️ En Controversia')], default='BORRADOR', max_length=20, verbose_name='Estado Factura'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='verification_notes',
            field=models.TextField(blank=True, verbose_name='Notas Verificación'),
        ),
        migrations.AddField(
            model_name='clientinvoice',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Facturado'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='invoice_date',
            field=models.DateField(verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='invoice_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='payment_status',
            field=models.CharField(choices=[('EMITIDA', 'Emitida'), ('COBRADA', 'Cobrada'), ('VENCIDA', 'Vencida'), ('PENDING', 'Pendiente'), ('PARTIAL', 'Parcial'), ('PAID', 'Pagada'), ('OVERDUE', 'Vencida'), ('PROBLEM', 'Problema')], default='PENDING', max_length=20, verbose_name='Estado Pago'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['status', 'due_date'], name='client_invo_status_85049a_idx'),
        ),
        migrations.AddIndex(
            model_name='clientinvoice',
            index=models.Index(fields=['project', 'status'], name='client_invo_project_84bae6_idx'),
        ),
    ]
