# Generated by Django 5.2.6 on 2025-10-15 01:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_alter_clientinvoice_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientinvoice',
            new_name='projects_cl_status_b24c41_idx',
            old_name='client_invo_status_85049a_idx',
        ),
        migrations.RenameIndex(
            model_name='clientinvoice',
            new_name='projects_cl_project_3f1445_idx',
            old_name='client_invo_project_84bae6_idx',
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monto total de la factura', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Facturado'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='bank_confirmation_code',
            field=models.CharField(blank=True, help_text='Código de confirmación del banco', max_length=50, verbose_name='Código Confirmación Banco'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='bank_reference',
            field=models.CharField(blank=True, help_text='Número de referencia del pago bancario', max_length=100, verbose_name='Referencia Bancaria'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='bank_verified_date',
            field=models.DateField(blank=True, help_text='Fecha cuando se verificó el pago en el banco', null=True, verbose_name='Fecha Verificación Banco'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='client_notes',
            field=models.TextField(blank=True, help_text='Comentarios o información proporcionada por el cliente', verbose_name='Comentarios del Cliente'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción de los servicios/proyectos facturados', verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='due_date',
            field=models.DateField(blank=True, help_text='Fecha límite para el pago', null=True, verbose_name='Fecha Vencimiento'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='fully_paid_date',
            field=models.DateField(blank=True, help_text='Fecha cuando se completó el proceso de pago', null=True, verbose_name='Fecha Pago Completo'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Notas internas del equipo', verbose_name='Notas Internas'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='invoice_date',
            field=models.DateField(help_text='Fecha cuando se emitió la factura al cliente', verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='invoice_number',
            field=models.CharField(help_text='Número único de factura (Ej: F-001, FAC-2024-001)', max_length=50, verbose_name='Número de Factura'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Marcar si requiere atención inmediata', verbose_name='Urgente'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monto real que se recibió en la cuenta', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto Pagado'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='payment_reported_date',
            field=models.DateField(blank=True, help_text='Fecha cuando el cliente reportó el pago', null=True, verbose_name='Fecha Reporte Pago'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='payment_status',
            field=models.CharField(default='PENDING', max_length=20, verbose_name='Estado Pago'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_invoices', to='projects.projects', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='reminder_sent',
            field=models.BooleanField(default=False, help_text='Indica si se envió recordatorio de pago', verbose_name='Recordatorio Enviado'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='reported_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que reportó el pago del cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='status',
            field=models.CharField(choices=[('BORRADOR', '📝 Borrador'), ('EMITIDA', '✅ Factura Emitida'), ('PAGO_REPORTADO', '🟡 Pago Reportado por Cliente'), ('PAGO_VERIFICADO', '🔵 Pago Verificado en Banco'), ('PAGADA', '💰 Pagada Confirmada'), ('VENCIDA', '❌ Vencida'), ('PAGO_NO_RECIBIDO', '🚨 Pago No Recibido'), ('CONTROVERSIA', '⚖️ En Controversia')], default='BORRADOR', help_text='Estado actual en el flujo de facturación', max_length=20, verbose_name='Estado Factura'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Observaciones durante la verificación bancaria', verbose_name='Notas Verificación'),
        ),
        migrations.AlterField(
            model_name='clientinvoice',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que verificó el pago en el banco', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Verificado por'),
        ),
        migrations.AlterModelTable(
            name='clientinvoice',
            table=None,
        ),
    ]
