# Generated by Django 5.2.6 on 2025-10-16 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_rename_client_invo_status_85049a_idx_projects_cl_status_b24c41_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monto del cambio (+ incremento, - reducción)', max_digits=12)),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente de Aprobación'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Revision', 'En Revisión')], default='Aprobado', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('change_date', models.DateField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, help_text='Referencia de orden de cambio/contrato', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_changes', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Cambio de Presupuesto',
                'verbose_name_plural': 'Cambios de Presupuesto',
                'db_table': 'budget_change',
            },
        ),
    ]
