# Generated by Django 5.2.6 on 2025-10-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_budgetchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(default='Inicial', max_length=60, verbose_name='Versión Baseline')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha inicio baseline')),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='Duración (meses)')),
                ('bac_planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='BAC planeado')),
                ('contract_planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Venta planeada')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Baseline de Proyecto',
                'verbose_name_plural': 'Baselines de Proyectos',
                'db_table': 'project_baseline',
            },
        ),
        migrations.CreateModel(
            name='ProjectMonthlyBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_index', models.PositiveIntegerField(verbose_name='Mes (1..n)')),
                ('pv_planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='PV planeado (S/)')),
                ('ev_planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='EV planeado (S/)')),
                ('ac_planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='AC planeado (S/)')),
                ('client_billing_planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Facturación cliente planeada (S/)')),
                ('progress_planned', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='% Avance plan')),
                ('label', models.CharField(blank=True, max_length=30, verbose_name='Etiqueta de mes (Enero 2025, etc.)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('baseline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='months', to='projects.projectbaseline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_baseline', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Baseline Mensual de Proyecto',
                'verbose_name_plural': 'Baselines Mensuales de Proyecto',
                'db_table': 'project_monthly_baseline',
                'ordering': ['project_id', 'month_index'],
                'unique_together': {('project', 'month_index')},
            },
        ),
    ]
