# Generated by Django 5.2.6 on 2025-11-05 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_projectbaseline_projectmonthlybaseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='chance',
            name='estimated_duration',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='chance',
            name='labor_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='chance',
            name='material_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='chance',
            name='overhead_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='chance',
            name='subcontracted_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='chance',
            name='total_costs',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='chance',
            name='aprox_uti',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
