# Generated by Django 5.2.6 on 2025-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_chance_estimated_duration_chance_labor_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chance',
            name='labor_cost_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='Costo Mano de Obra (%)'),
        ),
        migrations.AddField(
            model_name='chance',
            name='material_cost_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='Costo Material (%)'),
        ),
        migrations.AddField(
            model_name='chance',
            name='overhead_cost_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='Costo Gastos Generales (%)'),
        ),
        migrations.AddField(
            model_name='chance',
            name='profit_margin_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='Margen de Utilidad (%)'),
        ),
        migrations.AddField(
            model_name='chance',
            name='subcontracted_cost_pct',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=5, verbose_name='Costo Subcontratado (%)'),
        ),
    ]
