# Generated by Django 5.2.6 on 2025-11-05 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_chance_labor_cost_pct_chance_material_cost_pct_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presale',
        ),
    ]
