# Generated by Django 5.2.6 on 2025-11-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_delete_presale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podetailsupplier',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='podetailsupplier',
            name='supplier_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
