# Generated by Django 5.2.6 on 2025-11-06 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_alter_podetailsupplier_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='projects.purchaseorder', verbose_name='Orden de Compra relacionada'),
        ),
    ]
