# Generated by Django 5.2.6 on 2025-11-07 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_alter_invoice_purchase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='chance',
            name='currency',
            field=models.CharField(choices=[('PEN', 'Soles (S/)'), ('USD', 'Dólares ($)'), ('EUR', 'Euros (€)')], default='PEN', max_length=3, verbose_name='Moneda'),
        ),
    ]
