# Generated by Django 5.2.6 on 2025-11-07 00:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_chance_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='chance',
            name='aprox_uti_pen',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='chance',
            name='cost_aprox_chance_pen',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
        migrations.AddField(
            model_name='chance',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, verbose_name='Tipo de Cambio a S/'),
        ),
        migrations.AddField(
            model_name='chance',
            name='total_costs_pen',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12),
        ),
    ]
