# Generated by Django 5.2.6 on 2025-11-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_chance_aprox_uti_pen_chance_cost_aprox_chance_pen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chance',
            name='extra_cost_centers',
            field=models.JSONField(blank=True, default=list, help_text='Centros de costo adicionales (solo códigos)'),
        ),
    ]
