# Generated by Django 5.2.6 on 2025-11-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_chance_extra_cost_centers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chance',
            name='extra_cost_centers',
            field=models.JSONField(blank=True, default=list, help_text='Centros de costo adicionales (solo códigos)', null=True),
        ),
    ]
