# Generated by Django 5.2.6 on 2025-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0034_alter_chance_extra_cost_centers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
