# Generated by Django 4.2 on 2025-11-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_alter_purchaseorder_final_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinvoice',
            name='bank_reference',
            field=models.CharField(blank=True, default='', help_text='Número de referencia del pago bancario', max_length=100, null=True, verbose_name='Referencia Bancaria'),
        ),
    ]
