# Generated by Django 4.2 on 2025-11-21 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_alter_purchase_order_foreign_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='projects.purchaseorder', to_field='po_number', verbose_name='Orden de Compra relacionada'),
        ),
        migrations.AlterField(
            model_name='podetailproduct',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.purchaseorder', to_field='po_number'),
        ),
        migrations.AlterField(
            model_name='podetailsupplier',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.purchaseorder', to_field='po_number'),
        ),
    ]
