# Generated by Django 5.2.6 on 2025-11-21 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_alter_invoice_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='purchase_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='projects.purchaseorder', verbose_name='Orden de Compra relacionada'),
        ),
        migrations.AlterField(
            model_name='podetailproduct',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='podetailsupplier',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.purchaseorder'),
        ),
    ]
