# Generated by Django 4.2 on 2025-11-20 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0036_alter_purchaseorder_final_delivery_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('units_planned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_completed', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('planned_start', models.DateTimeField(blank=True, null=True)),
                ('planned_end', models.DateTimeField(blank=True, null=True)),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('IN_PROGRESS', 'En Progreso'), ('IN_REVIEW', 'En Revisión'), ('DONE', 'Hecho')], default='BACKLOG', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=0, help_text='Peso porcentual en el proyecto (0-100)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Tarea padre (para crear sub-tareas)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='tasks.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.projects')),
            ],
            options={
                'verbose_name': 'Tarea',
                'verbose_name_plural': 'Tareas',
                'db_table': 'tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de trabajo')),
                ('free_activity_name', models.CharField(blank=True, help_text='Si no es tarea asignada, describir qué se hizo', max_length=200, verbose_name='Actividad libre')),
                ('units_completed', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unidades completadas')),
                ('hours_start', models.TimeField(help_text='Hora en que empezó a trabajar', verbose_name='Hora inicio')),
                ('hours_end', models.TimeField(help_text='Hora en que terminó de trabajar', verbose_name='Hora fin')),
                ('comments', models.TextField(blank=True, help_text='Observaciones del trabajo realizado', verbose_name='Comentarios')),
                ('photos', models.ImageField(blank=True, help_text='Fotos del trabajo realizado', null=True, upload_to='work_logs/%Y/%m/', verbose_name='Fotos de evidencia')),
                ('status', models.CharField(choices=[('PENDING', '⏳ Pendiente Aprobación'), ('APPROVED', '✅ Aprobado'), ('REJECTED', '❌ Rechazado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_logs', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to='tasks.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]